---
- name: set firewall-zones
  include: set_firewall_zone.yml
  vars:
    name: "{{item.name}}"
    network: "{{item.network}}"
    forward: "{{item.forward | default({})}}"
    input: "{{item.input | default({})}}"
    output: "{{item.output | default({})}}"
    masq: "{{item.masq | default({})}}"
  with_items: "{{zones}}"

- name: set firewall-forwardings
  include: set_firewall_forwarding.yml
  vars:
    index: "{{item.0}}"
    src: "{{item.1.src}}"
    dest: "{{item.1.dest}}"
  with_indexed_items: "{{forwardings}}"

- name: set firewall-redirects
  include: set_firewall_redirect.yml
  vars:
    index: "{{item.0}}"
    name: "{{item.1.name}}"
    src: "{{item.1.src}}"
    proto: "{{item.1.proto}}"
    src_dport: "{{item.1.src_dport}}"
    dest_ip: "{{item.1.dest_ip}}"
    dest_port: "{{item.1.dest_port}}"
    target: "{{item.1.target}}"
    dest: "{{item.1.dest}}"
  with_indexed_items: "{{redirects}}"

- name: set firewall-rules
  include: set_firewall_rule.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name}}"
    family: "{{item.1.family | default({})}}"
    src: "{{item.1.src | default({})}}"
    src_ip: "{{item.1.src_ip | default({})}}"
    dest: "{{item.1.dest | default({})}}"
    dest_ip: "{{item.1.dest_ip | default({})}}"
    target: "{{item.1.target}}"
    enabled: "{{item.1.enabled | default(True)}}"
  with_indexed_items: "{{rules}}"
