---
- name: set firewall-zones
  include: set_firewall_zone.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name | default(item.1.network)}}"
    network: "{{item.1.network}}"
    forward: "{{item.1.forward | default({})}}"
    input: "{{item.1.input | default({})}}"
    output: "{{item.1.output | default({})}}"
    masq: "{{item.1.masq | default({})}}"
  with_indexed_items: "{{zones}}"

- name: set firewall-forwardings
  include: set_firewall_forwarding.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    src: "{{item.1.src}}"
    dest: "{{item.1.dest}}"
  with_indexed_items: "{{forwardings}}"

- name: set firewall-redirects
  include: set_firewall_redirect.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name}}"
    src: "{{item.1.src}}"
    proto: "{{item.1.proto}}"
    src_dport: "{{item.1.src_dport}}"
    dest_ip: "{{item.1.dest_ip}}"
    dest_port: "{{item.1.dest_port}}"
    target: "{{item.1.target}}"
    dest: "{{item.1.dest}}"
  with_indexed_items: "{{redirects}}"

- name: set firewall-rules
  include: set_firewall_rule.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name}}"
    family: "{{item.1.family | default({})}}"
    src: "{{item.1.src | default({})}}"
    src_ip: "{{item.1.src_ip | default({})}}"
    src_port: "{{item.1.src_port | default({})}}"
    dest: "{{item.1.dest | default({})}}"
    dest_ip: "{{item.1.dest_ip | default({})}}"
    dest_port: "{{item.1.dest_port | default({})}}"
    target: "{{item.1.target}}"
    enabled: "{{item.1.enabled | default(True)}}"
  with_indexed_items: "{{rules}}"

- name: set custom_rules
  include: set_custom_rule.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    name: "{{item.1.name | default({})}}"
    content: "{{item.1.content | default({})}}"
    reload: "{{item.1.reload | default({})}}"
  with_indexed_items: "{{custom_rules}}"