---
- name: set firewall-zone name
  uci:
    command: set
    config: "firewall"
    section: "{{name}}"
    option: "name"
    type: "zone"
    value: "{{name}}"
  notify:
    - uci commit firewall
    - reload network for openwrt-firewall

- name: set firewall-zone network
  uci:
    command: set
    config: "firewall"
    section: "{{name}}"
    option: "network"
    type: "zone"
    value: "{{network}}"
  notify:
    - uci commit firewall
    - reload network for openwrt-firewall

- name: set firewall-zone forward
  uci:
    command: set
    config: "firewall"
    section: "{{name}}"
    option: "forward"
    type: "zone"
    value: "{{forward}}"
  when: forward != {}
  notify:
    - uci commit firewall
    - reload network for openwrt-firewall

- name: set firewall-zone input
  uci:
    command: set
    config: "firewall"
    section: "{{name}}"
    option: "input"
    type: "zone"
    value: "{{input}}"
  when: input != {}
  notify:
    - uci commit firewall
    - reload network for openwrt-firewall

- name: set firewall-zone output
  uci:
    command: set
    config: "firewall"
    section: "{{name}}"
    option: "input"
    type: "zone"
    value: "{{output}}"
  when: output != {}
  notify:
    - uci commit firewall
    - reload network for openwrt-firewall
