---
- name: set custom_rule include content
  template:
    src: custom_rule.j2
    dest: "/etc/firewall.{{name}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-custom-rules
  uci:
    command: set_object
    config: firewall
    type: include
    index: "{{index}}"
    values:
      path: "/etc/firewall.{{name}}"
      reload: "{{ reload | int(None) }}"
  notify:
    - uci commit firewall
    - reload firewall
