---
- name: set firewall-rule name
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "name"
    value: "{{name}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule family
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "family"
    value: "{{family}}"
  when: family != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule src
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "src"
    value: "{{src}}"
  when: src != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule src_ip
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "src_ip"
    value: "{{src_ip}}"
  when: src_ip != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule src_port
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "src_port"
    value: "{{src_port}}"
  when: src_port != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule dest
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "dest"
    value: "{{dest}}"
  when: dest != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule dest_ip
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "dest_ip"
    value: "{{dest_ip}}"
  when: dest_ip != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule dest_port
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "dest_port"
    value: "{{dest_port}}"
  when: dest_port != {}
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule target
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "target"
    value: "{{target}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule enabled
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "enabled"
    value: "{{enabled | int}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-rule icmp_type
  uci:
    command: set
    config: "firewall"
    type: "rule"
    index: "{{index}}"
    option: "icmp_type"
    value: "{{icmp_type}}"
  when: icmp_type != {}
  notify:
    - uci commit firewall
    - reload firewall
