---
- name: set firewall-redirect name
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "name"
    type: "redirect"
    value: "{{name}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect src
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "src"
    type: "redirect"
    value: "{{src}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect proto
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "proto"
    type: "redirect"
    value: "{{proto}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect src_dport
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "src_dport"
    type: "redirect"
    value: "{{src_dport}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect dest_ip
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "dest_ip"
    type: "redirect"
    value: "{{dest_ip}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect dest_port
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "dest_port"
    type: "redirect"
    value: "{{dest_port}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect target
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "target"
    type: "redirect"
    value: "{{target}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect dest
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "dest"
    type: "redirect"
    value: "{{dest}}"
  notify:
    - uci commit firewall
    - reload firewall

- name: set firewall-redirect enabled
  uci:
    command: set
    config: "firewall"
    index: "{{index}}"
    option: "enabled"
    type: "redirect"
    value: "{{enabled | int}}"
  when: enabled != {}
  notify:
    - uci commit firewall
    - reload firewall
